Repository fossnsbm/hackovate-challenges, pull requests merged in 2023-10, with the labels that each got.

#17 1-dulannadeeja
  README.md
  dulannadeeja/assets/app.js
  dulannadeeja/assets/main.css
  dulannadeeja/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#19 Issue #1 | Hemsara
  README.md
  hemsara-react/hackovate-gun-app/.gitignore
  hemsara-react/hackovate-gun-app/README.md
  hemsara-react/hackovate-gun-app/package.json
  hemsara-react/hackovate-gun-app/public/favicon.ico
  hemsara-react/hackovate-gun-app/public/index.html
  hemsara-react/hackovate-gun-app/public/logo192.png
  hemsara-react/hackovate-gun-app/public/logo512.png
  hemsara-react/hackovate-gun-app/public/manifest.json
  hemsara-react/hackovate-gun-app/public/robots.txt
  hemsara-react/hackovate-gun-app/src/App.js
  hemsara-react/hackovate-gun-app/src/components/GunSelector.js
  hemsara-react/hackovate-gun-app/src/components/Guns.js
  hemsara-react/hackovate-gun-app/src/components/Inventories.js
  hemsara-react/hackovate-gun-app/src/index.js
  hemsara-react/hackovate-gun-app/src/index.scss
  hemsara-react/hackovate-gun-app/yarn.lock
Labels: Hacktoberfest, hacktoberfest-accepted, ISSUE #1

#22 Issue#1-swaggy2004
  1- Swaggy2004/main.html
  1- Swaggy2004/style.css
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#23 #1- Sithumsankajith
  README.md
  Sithumsankajith/issue.html
Labels: Hacktoberfest, hacktoberfest-accepted

#24 1-techie-ranith
  README.md
  techie-ranith/README.md
  techie-ranith/app.py
  techie-ranith/static/index.js
  techie-ranith/tailwind.config.js
  techie-ranith/templates/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#14 #1-AyoItsYas
  .eslintrc.json
  .gitignore
  README.md
  next.config.js
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/index.jsx
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  styles/Home.module.scss
  styles/globals.css
  tsconfig.json
  yarn.lock
Labels: Hacktoberfest, hacktoberfest-accepted

#25 2-dulannadeeja
  dulannadeeja/assets/app.js
  dulannadeeja/assets/main.css
  dulannadeeja/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#26 #1-Umayanga12
  README.md
  Umayanga12/Umayanga12.html
Labels: Hacktoberfest, hacktoberfest-accepted

#27 #issue2-Sithumsankajith
  Sithumsankajith/issue2.html
  Sithumsankajith/issue3.html
Labels: Hacktoberfest, hacktoberfest-accepted

#28 1-lakdilu20
  README.md
  lakdilu20/app.js
  lakdilu20/index.html
  lakdilu20/main.css
Labels: Hacktoberfest, hacktoberfest-accepted

#30 issue3
  Sithumsankajith/issue3.html
Labels: Hacktoberfest, hacktoberfest-accepted

#29 #2 | Hemsara
  hemsara-react/hackovate-gun-app/src/components/GunSelector.js
  hemsara-react/hackovate-gun-app/src/components/Guns.js
  hemsara-react/hackovate-gun-app/src/components/Inventories.js
  hemsara-react/hackovate-gun-app/src/index.scss
Labels: Hacktoberfest, hacktoberfest-accepted, ISSUE #2

#31 #1 - VinukaThejana
  vinukathejana/.eslintrc.json
  vinukathejana/.gitignore
  vinukathejana/README.md
  vinukathejana/bun.lockb
  vinukathejana/next.config.js
  vinukathejana/package.json
  vinukathejana/postcss.config.js
  vinukathejana/public/next.svg
  vinukathejana/public/vercel.svg
  vinukathejana/src/app/favicon.ico
  vinukathejana/src/app/globals.css
  vinukathejana/src/app/layout.tsx
  vinukathejana/src/app/page.tsx
  vinukathejana/tailwind.config.ts
  vinukathejana/tsconfig.json
Labels: Hacktoberfest, hacktoberfest-accepted

#34 Hemsara | issue #3
  hemsara-react/hackovate-gun-app/src/components/Guns.js
  hemsara-react/hackovate-gun-app/src/components/Inventories.js
  hemsara/hackovate-gun-app/node_modules/.cache/default-development/0.pack
  hemsara/hackovate-gun-app/node_modules/.cache/default-development/index.pack
Labels: Hacktoberfest, hacktoberfest-accepted, ISSUE #3

#37 #1-SaumyaSM
  README.md
  SaumyaSM/issue1.html
  SaumyaSM/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#32 1-ArvinFox
  ArvinFox/index.html
  ArvinFox/style.css
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#35 change
  .vscode/launch.json
  HIRUNIATHUKORALA.md
  Hiruniathukorala/index.html
  Hiruniathukorala/script.js
  Hiruniathukorala/styles.css
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#33 #Issue 1 - wijesuMM
  Meth Wijesundara/Meth.css
  Meth Wijesundara/Meth.html
  Meth Wijesundara/Meth.js
Labels: Hacktoberfest, hacktoberfest-accepted

#39 3-dulannadeeja
  dulannadeeja/assets/app.js
  dulannadeeja/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#47 4-Sithumsankajith
  Sithumsankajith/issue4.html
  Sithumsankajith/issue5.html
Labels: Hacktoberfest, hacktoberfest-accepted

#59 5-dulannadeeja
  dulannadeeja/assets/app.js
  dulannadeeja/assets/main.css
  dulannadeeja/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#40 Issue #4 and bug foxes | Hemsara
  hemsara-react/hackovate-gun-app/package.json
  hemsara-react/hackovate-gun-app/src/App.js
  hemsara-react/hackovate-gun-app/src/components/GunSelector.js
  hemsara-react/hackovate-gun-app/src/components/Guns.js
  hemsara-react/hackovate-gun-app/src/components/Inventories.js
  hemsara-react/hackovate-gun-app/src/index.scss
  hemsara-react/hackovate-gun-app/yarn.lock
Labels: Hacktoberfest, hacktoberfest-accepted, ISSUE #4

#54 2-Risini-33
  README.md
  Risini-33/1.html
  Risini-33/2.html
  Risini-33/2.js
Labels: Hacktoberfest, hacktoberfest-accepted

#74 Hemsara issue #5
  hemsara-react/hackovate-gun-app/src/components/GunSelector.js
Labels: ISSUE #5

#48 1-vismithaG
  Issue1 hackovate.html
Labels: Hacktoberfest, hacktoberfest-accepted

#44 1-techie-ranith
  .gitignore
  techie-ranith/requirements.txt
  techie-ranith/tailwind.config.js
  techie-ranith/templates/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#80 3-Risini-33
  Risini-33/3.html
Labels: Hacktoberfest, hacktoberfest-accepted

#82 #1-Isuru-Eranda
  Isuru-Eranda/index.html
  Isuru-Eranda/style.css
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted, ISSUE #1

#79 1-madhuva25
  README.md
  madhuva/Madhuva.html
  madhuva/hm.css
Labels: Hacktoberfest, hacktoberfest-accepted, ISSUE #1

#58 NanayakkaraAR
  .DS_Store
  ashinireshana/ashinireshana.css
  ashinireshana/ashinireshana.html
Labels: Hacktoberfest, hacktoberfest-accepted, ISSUE #1

#67 #1 - JMADIKARI
  JMADIKARI/ISSUE 1.html
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted, ISSUE #1

#68 Issue#2-swaggy2004
  1- Swaggy2004/main.html
  1- Swaggy2004/script.js
  1- Swaggy2004/style.css
Labels: Hacktoberfest, hacktoberfest-accepted, ISSUE #2

#70 1-RAWINISATHEESHA
  .vscode/launch.json
  RAWINISATHEESHA/index.html
  RAWINISATHEESHA/index2.html
  RAWINISATHEESHA/styles.css
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted, ISSUE #1

#73 5-Sithumsankajith
  Sithumsankajith/issue5.html
Labels: Hacktoberfest, hacktoberfest-accepted, ISSUE #5

#84 #2-Isuru-Eranda
  Isuru-Eranda/index.html
  Isuru-Eranda/script.js
Labels: Hacktoberfest, hacktoberfest-accepted

#88 #3-Isuru-Eranda
  Isuru-Eranda/index.html
  Isuru-Eranda/script.js
  Isuru-Eranda/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#87 commited 2
  Meth Wijesundara/Meth.css
  Meth Wijesundara/Meth.html
  image.png
Labels: Hacktoberfest, hacktoberfest-accepted

#94 feat:
  Meth Wijesundara/504563-Sniper-Hitman.jpg
  Meth Wijesundara/Meth.css
  Meth Wijesundara/Meth.html
  Meth Wijesundara/Meth.js
  Meth Wijesundara/Meth2.js
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#93 #5-Isuru-Eranda
  Isuru-Eranda/index.html
  Isuru-Eranda/script.js
  Isuru-Eranda/style.css
Labels: Hacktoberfest, hacktoberfest-accepted, ISSUE #5

#95 Issue #2 - Implemented Selection of Menu Items
  components/index/ItemMenu.module.scss
  components/index/ItemMenu.tsx
  pages/_document.tsx
  pages/index.tsx
Labels: Hacktoberfest, hacktoberfest-accepted
